"""create weather_requests

Revision ID: 3020cc085af2
Revises: 
Create Date: 2025-10-22 13:19:26.714583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3020cc085af2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_requests',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('lat', sa.DOUBLE_PRECISION(), nullable=False),
    sa.Column('lon', sa.DOUBLE_PRECISION(), nullable=False),
    sa.Column('weather_main', sa.TEXT(), nullable=False),
    sa.Column('temp', sa.DOUBLE_PRECISION(), nullable=False),
    sa.Column('wind_speed', sa.DOUBLE_PRECISION(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_weather_requests_id'), 'weather_requests', ['id'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_weather_requests_id'), table_name='weather_requests', schema='public')
    op.drop_table('weather_requests', schema='public')
    # ### end Alembic commands ###
